name: Terraform_4th Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        type: choice
        options:
          - dev
          - qa
jobs:

  plan:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - name: Terraform plan
        run: |
         terraform plan \
           -var="environment=${{ github.event.inputs.environment }}".tfvars \
           -out=tfplan2

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan2
          path: tfplan2

  apply:

    needs: plan

    runs-on: ubuntu-latest

    environment:
      name: Production

    steps:

      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - run: terraform init

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan2

      - name: terraform apply \
        run: |
          terraform apply \
            -auto-approve \
            -var-file="${{ github.event.inputs.environment }}.tfvars"